### PR TITLE
Use `files` property in package.json

### PR DESCRIPTION
**Pull request by kevva**

### CODE REVIEW

**Comment by shinnn** [comment]
+1

test/out.json is over 250kb.

**Comment by fb55** [comment]
Thanks to both of you (also for #8)!

**Comment by shinnn** [comment]
@fb55 No problem! I'd be glad if you release a new version :)

**Comment by fb55** [comment]
Apparently @npm has problems with the name again: https://github.com/npm/npm/issues/4665. I can't publish a new version right now, but would be willing to switch the package to a lowercase name (if old references could be redirected).

cc @othiym23 @isaacs

**Comment by shinnn** [comment]
Oh, I didn't know that problem.

**Comment by isaacs** [comment]
@fb55 Existing packages should be fine.  You can push updates to them.  you just can't create NEW packages with uppercase letters in the name, afaik.

If you want to lowecase it, you can soft-redirect with the `npm deprecate` command.

**Comment by fb55** [comment]
@isaacs This is the response I get:

```
feedy at feedy in ~/Documents/node_modules/CSSwhat on master [?]
$ npm pub
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "pub"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0

npm ERR! Invalid name: "CSSwhat"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/feedy/Documents/node_modules/CSSwhat/npm-debug.log
```

**Comment by isaacs** [comment]
@fb55 Yeah, I get it.  I see, it's validating before sending to the registry.  That feels like a reasonably-motivated idea that is unfortunately causing some unpleasant behavior in this case.  We should be rejecting new package creation with uppercase names, but not updates to existing packages.

I'll bring it up with the team here.

**Comment by fb55** [comment]
Thanks @isaacs!

**Pull request merged**
